"""3

Revision ID: a60141e591b5
Revises: b75a06d8c8ed
Create Date: 2024-08-26 11:48:45.186805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a60141e591b5'
down_revision: Union[str, None] = 'b75a06d8c8ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_date', sa.Date(), nullable=True))
    op.drop_column('books', 'publication_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publication_data', sa.DATE(), nullable=True))
    op.drop_column('books', 'publication_date')
    # ### end Alembic commands ###
